"""empty message

Revision ID: 13cbc51f4847
Revises: f9a22c66cd39
Create Date: 2024-05-04 16:17:51.216627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13cbc51f4847'
down_revision = 'f9a22c66cd39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_msj', schema=None) as batch_op:
        batch_op.drop_constraint('contact_msj_to_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_msj', schema=None) as batch_op:
        batch_op.create_unique_constraint('contact_msj_to_key', ['to'])

    # ### end Alembic commands ###
