"""empty message

Revision ID: dd907e6df0c9
Revises: 7a1261be3dee
Create Date: 2024-04-29 19:21:22.686279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd907e6df0c9'
down_revision = '7a1261be3dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_msj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to', sa.Integer(), nullable=False),
    sa.Column('from_user', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['to'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('to')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_msj')
    # ### end Alembic commands ###
